version: '3'
services:
  db:
    container_name: "django_db"
    image: postgres:11.1
    restart: always
    ports:
      - 5432:5432
  web:
    container_name: "django_web"
    build: docker/dev/
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=settings.dev