version: '3'
services:
  db:
    container_name: db_dj
    image: postgres
    restart: always
    ports:
      - 5432:5432
  web:
    build: .
    container_name: server_dj
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
