# Generated by Django 2.1.5 on 2019-01-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='parent',
        ),
    ]
