# Generated by Django 2.1.5 on 2019-01-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_post_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='parent',
        ),
    ]
