# Generated by Django 2.1.5 on 2019-01-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
