# Generated by Django 2.1.3 on 2018-12-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deck_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(to='cards.Cards'),
        ),
    ]
