# Generated by Django 2.1.5 on 2019-01-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190112_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='user',
            name='follow',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
