# Generated by Django 2.1.5 on 2019-01-20 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190112_1552'),
        ('user', '0005_auto_20190113_1641'),
    ]

    operations = [
    ]
