# Generated by Django 2.1.1 on 2018-11-13 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('attack', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(10)])),
                ('img', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='type_card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Type_Card'),
        ),
    ]
