# Generated by Django 2.1.3 on 2018-11-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='type_card_id',
            new_name='type_card',
        ),
    ]
