# Generated by Django 2.1.5 on 2019-01-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_cards',
            name='card',
        ),
        migrations.RemoveField(
            model_name='user_cards',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_cards',
        ),
    ]
