# Generated by Django 2.1.3 on 2018-11-13 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='attack',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='card',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
