# Generated by Django 2.1.3 on 2018-11-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20181117_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Type_Card',
            new_name='Rarity_card',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='type_card',
            new_name='rarity_card',
        ),
        migrations.AddField(
            model_name='card',
            name='race_card',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='cards.Race_card'),
            preserve_default=False,
        ),
    ]
