# Generated by Django 2.1.4 on 2019-01-07 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0004_auto_20181125_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_cards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card', models.ManyToManyField(to='cards.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
