# Generated by Django 2.1.3 on 2018-12-04 14:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_auto_20181204_1439'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0004_auto_20181125_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('attack', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('health', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('img', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race_cards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rarity_cards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_cards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cards', models.ManyToManyField(to='cards.Cards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='race_card',
        ),
        migrations.RemoveField(
            model_name='card',
            name='rarity_card',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Race_card',
        ),
        migrations.DeleteModel(
            name='Rarity_card',
        ),
        migrations.AddField(
            model_name='cards',
            name='race_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Race_cards'),
        ),
        migrations.AddField(
            model_name='cards',
            name='rarity_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Rarity_cards'),
        ),
    ]
