# Generated by Django 2.1.3 on 2019-01-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20181204_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_cards',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='user_cards',
            name='user',
        ),
        migrations.AlterField(
            model_name='rarity_cards',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='User_cards',
        ),
    ]
